### ISSUE TITLE
No translations ?

### ISSUE THREAD

**Issue by grizzlylab** [rollerworks/PasswordStrengthBundle#55] opened 2015-10-16 19:20 UTC
e.g. "password_too_weak"
I can add some translations (pull request) if you point me to the right direction.

**Comment by grizzlylab** [comment] 2015-10-16 19:22
Actually, we just need some messages.xx.yml in the bundle.

**Comment by sstok** [comment] 2015-10-17 13:17
Duplicate of #27

**Closed by sstok** 2015-10-17 13:17 UTC
Labels: duplicate
